### ISSUE TITLE
Changing the patch file destination creates invalid output path

### ISSUE THREAD

**Issue by McBaws** [dan0v/xdelta3-cross-gui#37] opened 2024-09-15 06:03 UTC
When I start the program and drag in my first input file, the `Patch file(s) destination` autofills with a proper file path.
However, when I try changing the output folder with the `...` next to `Patch file(s) destination`, the new file path has percent-codes and forward slashes in it, as if it's a URL. 

For example:
After dragging in the first input file, the output is
`...\Chainsaw Man\[sam] Chainsaw Man [BD 1080p FLAC]\Extras\xDelta3_Output`
If I use the `...` and reselect this folder, it becomes
`.../Chainsaw%20Man/%5Bsam%5D%20Chainsaw%20Man%20%5BBD%201080p%20FLAC%5D/Extras`

Additional Info: I am using version 1.6.1 on Windows 11

**Comment by dan0v** [comment] 2024-09-22 13:49
Thanks for reporting. I'm on holiday atm, so will take a look when I'm back in a week or so. Strangely I didn't see this behaviour when I made some changes to the path selection logic in the last release, but it was probably caused by that. You could try using a previous version for now and seeing if the issue is resolved.

**Comment by dan0v** [comment] 2024-10-01 17:12
Resolved in [1.6.2](https://github.com/dan0v/xdelta3-cross-gui/releases/tag/1.6.2)

**Closed by dan0v** 2024-10-01 17:12 UTC
